// <auto-generated />
namespace Gallery.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddUniqueIndexesFor_RoleName_MediaPath_MediaType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUniqueIndexesFor_RoleName_MediaPath_MediaType));
        
        string IMigrationMetadata.Id
        {
            get { return "202005220017309_AddUniqueIndexesFor_RoleName_MediaPath_MediaType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
